### ISSUE TITLE
ACC: Ki és bekapcsolhatóság implementálása

### ISSUE THREAD

**Issue by vaghylevente** [SzFMV2022-Osz/AutomatedCar-A#118]
Definition of Done
- [x] C gomb lenyomására a tempomat kapcsoljon ki/be (InputPacket.CruiseControlInput == TurnOnOrOff)
- [x] Bekapcsoláskor a célsebessége az aktuális sebesség, de a minimum célsebesség 30 km/h

**Comment by MondokIstvan** [comment]
Pressing button "C" switches ACC On or Off and set target speed to 30km/h if activated at a lower speed than 30km/h or set to 160km/h if activated at higher than 160km/h.
