### ISSUE TITLE
Közös absztrakció szenzoroknak

### ISSUE THREAD

**Issue by erosd99** [SzFMV2022-Osz/AutomatedCar-A#22]
Definition of Done:

- [x] Minden szenzor tud kommunikálni Virtual Function Bus-al
- [x] Minden szenzor ki tudja olvasni a kocsi pillanatnyi pozícióját
- [x] Minden szenzor be tudja írni a Virtual Function Bus-ba az általa Relevánsnak nyilvánított objektumokat

**Comment by szeal12300** [comment]
duplicate issue - see skeleton (szenzorok absztrakciója) #7 issue
