### ISSUE TITLE
INPC interfész

### ISSUE THREAD

**Issue by vaghylevente** [SzFMV2022-Osz/AutomatedCar-A#29]

**Comment by roliii01** [comment]
Nem csináltam alap Npc osztályt, mivel akkor a Car osztályt nem tudtam volna meghívni a CarNpc-re.

**Comment by vaghylevente** [comment]
A Car osztályra az lett megbeszélve, hogy nincs rá szükségünk, mivel úgy is csak egy tulajdonsága van. Az NPC osztály célja meg az lenne, hogy az NPCCar és NPCPerson (és NPCOther) közös tulajdonságait összefogja, így elkerülve a kódismétlést. Viszont most kiderült, hogy a VirtualFunctionBus nem lehet az INPC interfészben, ezért azt is az NPC osztályban kellene majd előírni.

**Comment by erosd99** [comment]
@vaghylevente erről majd beszéljünk holnap pls, VFB-t nem szabadna csinálnia, mert a belső DispatcherTimer Dispatchere megöli a játék szinkronizálását (Avalonia specifikus faszság, http://reference.avaloniaui.net/api/Avalonia.Threading/Dispatcher/) 

Vagy fel kéne iratkozni a car VFB-re (nettó faszság), vagy ki kéne szedni VFB-t a Carból, és Singletonba dobni (megint nettó faszság).
