### ISSUE TITLE
NPCCar osztály

### ISSUE THREAD

**Issue by vaghylevente** [SzFMV2022-Osz/AutomatedCar-A#32]
Definition of done:
- [x] Megvalósítja az INPC interfészt
- [x] A bejárandó útvonalat konstruktoron keresztül kapja
- [x] WorldObjectType beállítása
- [x] MoveComponent példányosítása
- [x] MoveComponent regisztrálása a VirtualFunctionBus-ban

**Comment by vaghylevente** [comment]
- [ ] Megvalósítja az INPC interfészt

**Comment by DavidGgly** [comment]
Miért valósítsa meg az `abstract class NPC`-t és az `interface INPC`-t is? Mindkettő előír neki egy `Move()` metódust, de nem látom, minek.

**Comment by vaghylevente** [comment]
Igazad van, az NPC classból majd kiszedem.

**Comment by vaghylevente** [comment]
Done.
