### ISSUE TITLE
Powertrain osztály elkészítése

### ISSUE THREAD

**Issue by Totable** [SzFMV2022-Osz/AutomatedCar-A#40]
Ez az osztály kapcsolja össze a Messengert a kormánnyal és a motorral. Az utóbbi osztályok megfelelő metódusait aszinkron indítja, majd megvárja a kért metódusok végrehajtását. Ezután a kapott vektorokat összegzi és továbbadja a VFB, illetve a többi adatot pl.: sebesség, kormányállás....

**Comment by daniinad2** [comment]
Tartalmazzon egy motort, egy váltót és egy kormányművet
