### ISSUE TITLE
NPC osztály

### ISSUE THREAD

**Issue by vaghylevente** [SzFMV2022-Osz/AutomatedCar-A#42]
- [x] Előírja a VirtualFunctionBus-t

**Comment by vaghylevente** [comment]
Hiányzik: Routes osztály

**Comment by erosd99** [comment]
@vaghylevente erről majd beszéljünk holnap pls, VFB-t nem szabadna csinálnia, mert a belső DispatcherTimer Dispatchere megöli a játék szinkronizálását (Avalonia specifikus faszság, http://reference.avaloniaui.net/api/Avalonia.Threading/Dispatcher/)

Vagy fel kéne iratkozni a car VFB-re (nettó faszság), vagy ki kéne szedni VFB-t a Carból, és Singletonba dobni (megint nettó faszság).

**Comment by erosd99** [comment]
Vaaaaagy kipulloljuk az ütemezést VFB-ből, és akkor kezdünk is hasonlítani egy normális játékra, vaaagy kihagyjuk VFB-t teljesen NPCkből, és kapnak saját ütemezést, amivel azért elég menőn lehet demonstrálni, hogy nem hardcoded megállási helyeink vannak :100: :fire:  :fire:  Szóval ja, ilyeneket kéne brainstormingolni :smile:

**Comment by vaghylevente** [comment]
Hát ez valóban érdekes. Most erre hirtelen nem tudom a megoldást.

**Comment by vaghylevente** [comment]
Viszont ConrolledCar-ból is alapból több van, szóval lehet mégis működni fog a több VFB.

**Comment by vaghylevente** [comment]
Done.
